name: hive_storage_service
description: A service for managing storage with Hive.
version: 1.1.3

environment:
  sdk: ">=3.8.0 < 4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mockito: ^5.3.2
  json_annotation: ^4.9.0
  build_runner: ^2.10.4
  http_cache:
    path: /Users/gerhard/Code/dart_packages/http_cache
  faker: ^2.2.0
  hive_ce_generator: ^1.10.0

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
