name: hive_storage_service
description: A service for managing storage with Hive.
version: 1.1.3

environment:
  sdk: ">=3.5.3 < 4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mockito: ^5.3.2
  json_annotation: ^4.9.0
  build_runner: ^2.3.3
  hive_generator: ^2.0.0
  http_cache:
    path: /Users/gerhard/Code/dart_packages/http_cache
  faker: ^2.2.0

dependencies:
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter:
    sdk: flutter
  package_info_plus: ^9.0.0
  path_provider: ^2.1.5
